// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoHead.proto

package protocol.head;

public final class ProtoHead {
  private ProtoHead() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   **
   *消息头类型，ENUM采用大写驼峰
   * </pre>
   *
   * Protobuf enum {@code protocol.EMsgHead}
   */
  public enum EMsgHead
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN_REQ = 0;</code>
     */
    LOGIN_REQ(0),
    /**
     * <code>LOGIN_RSP = 1;</code>
     */
    LOGIN_RSP(1),
    /**
     * <code>KEEP_ALIVE_REQ = 2;</code>
     */
    KEEP_ALIVE_REQ(2),
    /**
     * <code>KEEP_ALIVE_RSP = 3;</code>
     */
    KEEP_ALIVE_RSP(3),
    /**
     * <code>SYSTEM_REQ = 4;</code>
     */
    SYSTEM_REQ(4),
    /**
     * <code>SYSTEM_RSP = 5;</code>
     */
    SYSTEM_RSP(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LOGIN_REQ = 0;</code>
     */
    public static final int LOGIN_REQ_VALUE = 0;
    /**
     * <code>LOGIN_RSP = 1;</code>
     */
    public static final int LOGIN_RSP_VALUE = 1;
    /**
     * <code>KEEP_ALIVE_REQ = 2;</code>
     */
    public static final int KEEP_ALIVE_REQ_VALUE = 2;
    /**
     * <code>KEEP_ALIVE_RSP = 3;</code>
     */
    public static final int KEEP_ALIVE_RSP_VALUE = 3;
    /**
     * <code>SYSTEM_REQ = 4;</code>
     */
    public static final int SYSTEM_REQ_VALUE = 4;
    /**
     * <code>SYSTEM_RSP = 5;</code>
     */
    public static final int SYSTEM_RSP_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EMsgHead valueOf(int value) {
      return forNumber(value);
    }

    public static EMsgHead forNumber(int value) {
      switch (value) {
        case 0: return LOGIN_REQ;
        case 1: return LOGIN_RSP;
        case 2: return KEEP_ALIVE_REQ;
        case 3: return KEEP_ALIVE_RSP;
        case 4: return SYSTEM_REQ;
        case 5: return SYSTEM_RSP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EMsgHead>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EMsgHead> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EMsgHead>() {
            public EMsgHead findValueByNumber(int number) {
              return EMsgHead.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protocol.head.ProtoHead.getDescriptor().getEnumTypes().get(0);
    }

    private static final EMsgHead[] VALUES = values();

    public static EMsgHead valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EMsgHead(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protocol.EMsgHead)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ProtoHead.proto\022\010protocol*p\n\010EMsgHead\022" +
      "\r\n\tLOGIN_REQ\020\000\022\r\n\tLOGIN_RSP\020\001\022\022\n\016KEEP_AL" +
      "IVE_REQ\020\002\022\022\n\016KEEP_ALIVE_RSP\020\003\022\016\n\nSYSTEM_" +
      "REQ\020\004\022\016\n\nSYSTEM_RSP\020\005B\037\n\rprotocol.head\252\002" +
      "\rprotocol.headb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
